---

- name: Configures a server with the base_packages
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: true
  environment:
    PATH: '{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
  roles:
    - base_packages
  tasks:
# NOTE: this is required because SELinux was set to enforcing and we had to disable it
    - name: Reboot server
      ansible.builtin.reboot:
        reboot_timeout: 3600