---

- name: Configures a server with the base_packages
  hosts: 127.0.0.1
  connection: local
  become: true
  gather_facts: true
  environment:
    PATH: '{{ ansible_env.PATH }}:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
  roles:
    - base_packages
    - security